name: Main to Production

on:
  push:
    branches:
      - main

jobs:
  copy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "11poggie11"
          git config --global user.email "492992@student.fontys.nl"

      - name: Switch to production branch
        run: |
          git checkout production
          git merge main --no-ff --no-edit
          git push origin production
