name: Main to Production
on:
  push:
    branches:
      - main
jobs:
  copy-to-production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Copy files to production branch
      run: |
        rm -r test
        git clone https://github.com/11Poggie11/test.git $tmp_merge
        cd $tmp_merge
        git checkout production
        git merge main
        git push -u origin production
        11Poggie11
        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
