name: Main to Production
on:
  push:
    branches:
      - main
jobs:
  copy-to-production:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Copy files to production branch
      run: |
        git config --global user.email "492992@student.fontys.nl"
        git config --global user.name "11Poggie11"
        git checkout -b production
        git add .
        git commit -m "Copy main branch to production branch"
        git push -u origin production
